### PR TITLE
Text case formatting done

### LINKED ISSUE #90: Display text case should be modified before display
change the case of every display text

### PR DESCRIPTION
**Pull request by anuj1511**
Currently given title case to almost all the fields

### CODE REVIEW

**Comment by anuj1511** [comment]
I have created functions, which are giving deployment errors Sir. I am not able to get what's the exact problem in them.

**Comment by rishabhborn2win** [comment]
image

**Comment by rishabhborn2win** [comment]
@anuj1511 I have highlighted the error in the above SS so just try to fix that

**Comment by anuj1511** [comment]
Sir, I tried to export this in different ways but it is giving error

**Comment by rishabhborn2win** [comment]
Ok else everything mentioned in the issue is fixed?

**Comment by rishabhborn2win** [comment]
@anuj1511 But I am not able to see any of your commit after my review what you tried just push it.

**Comment by rishabhborn2win** [comment]
Bring all the functions outside the pages folder and import it from outside

**Pull request merged**
