### PR TITLE
Frontend integration

### PR DESCRIPTION
**Pull request by anuj1511**

### CODE REVIEW

**Comment by rishabhborn2win** [comment]
Fix this error and pass the vercel deployment so that we can test the integration part online.
Screenshot 2022-01-18 at 9 41 05 PM

**Comment by rishabhborn2win** [comment]
Screenshot 2022-01-18 at 9 43 36 PM




Again the same error.
One thing please confirm that are you guys able to see the logs?

**Comment by anuj1511** [comment]
Yes sir we are working on these errors, trying to resolve them

**Comment by rishabhborn2win** [comment]
@anuj1511 what is the update?

**Pull request closed without merging**
