### PR TITLE
Request count is displayed, Not logged in message

### LINKED ISSUE #102: Navbar buttons should be different according to the authentication status
Buttons like listing dashboard are of no use if you are not logged and make that pages private too as if the cookie is not there they should be redirected to signin page instead of displaying message.

### PR DESCRIPTION
**Pull request by anuj1511**
If we access any page without login then not logged in mesage will be shown

### CODE REVIEW

**Comment by rishabhborn2win** [comment]
@anuj1511 you can't use react hooks using a conditional statement so fix that and there are some more small fixes.

**Comment by anuj1511** [comment]
Done sir

**Comment by anuj1511** [comment]
There was one error sir in normal jsx. Made a component and if the user is not logged in then another component should be shown and not the page but it was changing the whole structure of the page

**Comment by rishabhborn2win** [comment]
Now its working fine but if the user is not signed in then what is the use of the nav bar simply remove that nav bar from the homepage and just keep the signin card thats it

**Comment by rishabhborn2win** [comment]
and try to add a icon in the place of view charges

**Comment by rishabhborn2win** [comment]
Not logged in is working fine

**Comment by rishabhborn2win** [comment]
Request count is also working fine

**Comment by rishabhborn2win** [comment]
Screenshot 2022-02-09 at 1 24 43 AM
One feature addition if we click on this button then we can directly redirect to the particular site page

**Comment by rishabhborn2win** [comment]
Currently I am merging this PR

**Comment by rishabhborn2win** [comment]
I will create these features as issue and assign it to you so that you can work it on separately.

**Comment by rishabhborn2win** [comment]
this PR merge break the accept request feature

**Pull request merged**
